#워커 프로세스 설정 
events {}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  # $spa 기본값 선언(모든 요청 기본 0)
  map $request_uri $spa {
    ~^/api/ 0;
    default 1;
  }
    # 로그 포맷 정의
  log_format frontend '$remote_addr - $remote_user [$time_local] "$request" ' #ip 주소 , 사용자, 시간, http 요청 +url + 프로토콜
                      'status=$status bytes=$body_bytes_sent '                #응답 상태 코드, 바이트 전송량
                      'route="$request_uri" req_time=$request_time '           #요청된 URI, 요청 처리 시간
                      'spa=$spa host="$host" http_host="$http_host" hostport="$host:$server_port" ' #host 정보 , 헤더 원본
                      'referer="$http_referer" ua="$http_user_agent"';          #유입 경로

  log_format api      '$remote_addr - $remote_user [$time_local] "$request" '  #ip 주소 , 사용자, 시간, http 요청 +url + 프로토콜
                      'status=$status upstream_status=$upstream_status '        #응답 상태 코드, 업스트림 상태 코드
                      'rt=$request_time urt=$upstream_response_time '           #요청 처리 시간, 업스트림 응답 시간
                      'host=$host referer="$http_referer" ua="$http_user_agent"'; #host 정보 , 유입 경로 , 사용자 에이전트

  upstream api {
    server api:4000;
  }
  server {
    listen 80;
    # 에러 로그
    error_log /var/log/nginx/error.log warn;
    root /usr/share/nginx/html;
    index index.html;

    # 프론트엔드 로그
    access_log /var/log/nginx/frontend.access.log frontend;

    # 프론트 (Vue)
    location / {
      # frontend 컨테이너의 3000 포트로 트래픽 전달
      try_files $uri $uri/ /index.html;
    }

    # API
    location /api/ {
      # API 호출 로그
      access_log /var/log/nginx/api.access.log api;

      proxy_pass http://api;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
